In [24]:
import pandas as pd

df = pd.read_csv("data/marketing_sample_with_brands.csv")

print("Number of rows: ", len(df))

number_of_nans = df["brand"].isna().sum()
print(f"Number of NaNs: {number_of_nans}")

df.sample(10)

Number of rows:  9484
Number of NaNs: 477

,asin_name,asin_value_usd,brand
7774,Rubie's Marvel Avengers: Endgame Child's Delux...,17.18,Rubie's Marvel
182,"Lionel FasTrack Electric O Gauge, O36 Curve Tr...",21.99,O36 Curve Track
7277,Klear Vu Tyson XL Overstuffed Fabric Cushion L...,18.99,Single Pad
1131,Melissa & Doug Playful Puppy Wooden Pull Toy f...,21.00,Melissa & Doug Playful Puppy
2423,DC Collectibles DC Artists Alley: Batman by No...,34.99,DC Collectibles
7941,Star Ace Toys Harry Potter & The Prisoner of A...,174.99,Azkaban
8243,Airfield Concrete Tarmac Section 1/72,19.99,Airfield
9275,Star Wars Anakin to Darth Vader Color Change L...,62.98,Star Wars
1637,Mongoose Kids Mountain Bike Helmet Zone Collec...,22.99,Mongoose Kids
6578,K2 Skate Men's MOD 110 Inline Skate,329.14,K2 Skate Men's

In [25]:
# Find asin_name with Apple
df[df["asin_name"].str.contains("Apple")]

,asin_name,asin_value_usd,brand
1276,FREEing Bungo Stray Dogs: Dead Apple: Akutagaw...,39.81,FREEing Bungo
3673,My Little Pony the Movie Applejack Sea-Pony Sm...,3.16,My Little
4366,"Tiny Love Explore and Play Apple, Red, One Size",7.99,Tiny Love
4438,"Bepuzzled Original 3D Crystal Puzzle - Apple, ...",11.99,Bepuzzled
4711,Amscan School Colors Graduation Party 3-D Mort...,10.50,Stars Foil Garland Decoration
6771,MasterPieces Family Hour Apple of My Eye Farm ...,11.99,MasterPieces
6874,"Baby Doll Bedding Regal Window Valance, Green ...",20.70,Green Apple
8360,Rubie's Costume Kids Ever After High Dragon Ga...,22.99,Rubie's Costume
9190,Premier Energizer Car Charger Adapter with And...,12.99,Android Type-C
9285,"Noch 25113 Apple Tree 3-1/8"" 3/ H0,Tt Scale Mo...",8.65,Noch 25113 Apple
9300,Hape Toddler Fruit Basket |Soft Pretend Food P...,20.00,Hape Toddler Fruit

In [6]:
df[df["brand"].isna()]

                                              asin_name  asin_value_usd brand
0     DB Longboards CoreFlex Crossbow 41" Bamboo Fib...          237.68   NaN
2     3Doodler Create Flexy 3D Printing Filament Ref...           34.99   NaN
7     Hoffmaster 120813 Double-Tipped Triangular Cra...           97.68   NaN
10    Moonlite, 3-Story Bundle for Boys, Includes 3 ...           18.16   NaN
11    DC Cover Girls: Black Canary by Joëlle Jones S...           84.61   NaN
...                                                 ...             ...   ...
9455  Tactic 54275 X-Tiles Board Game | Children & F...           12.00   NaN
9458                          30th Birthday Fabric Sash            6.67   NaN
9460  Beistle 55360-G FR Jumbo Crepe Streamer, 500-Feet            6.50   NaN
9464  The Stupell Home Décor Collection Mermaid Off ...           29.99   NaN
9465  Shapemags 100 Piece Tiles Set Clear Colors Mag...           41.99   NaN

[1412 rows x 3 columns]